### ISSUE TITLE
Error in sorting components at Nav

### ISSUE THREAD

**Issue by theus** [Malvid/Malvid#12]
I was cataloging some components in this model `component-option-N` and I found a mistake in sorting of order.

![image](https://user-images.githubusercontent.com/61322/43521093-675b34b4-956b-11e8-8408-fa22a1ad47ec.png)

**Comment by electerious** [comment]
Switching to `.localeCompare` might fix this issue. I will do some tests with it. Thanks for reporting it!

**Comment by electerious** [comment]
Fixed in the next version: https://github.com/Malvid/Malvid/commit/126a24cd25c7f4c1fd14248a1de4a5a9c78e1033
