### ISSUE TITLE
Cannot find module 'ora'

### ISSUE THREAD

**Issue by emsuiko** [Malvid/Malvid#26]
I followed the [Get Started-Guide](https://github.com/Malvid/Malvid/blob/master/docs/Get%20started.md#3-run-malvid) up to following point:
```
[16:51:30] anett:malvid-test $ npx malvid index.html index.html.json
npx: Installierte 337 in 8.011s
Cannot find module 'ora'
```
Globally installing ora didn't work, I initialized npm and installed malvid and ora locally. That worked.
Maybe there's a dependency missing or something?

**Comment by electerious** [comment]
Hm, I'm not using a module with this name so I guess that it's a sub-dependency with a missing dependency declaration. You could try to install malvid + ora manually:

```
npm init --yes
npm install malvid
npm install ora
./node_modules/.bin/malvid index.html index.html.json
```

**Comment by kabadesu** [comment]
Hey @electerious, it's required here:

https://github.com/Malvid/Malvid/blob/d795eb96e549d8650846e8583b6ff001a39c5633/bin/malvid#L7

**Comment by electerious** [comment]
Thanks for letting me know! Added the missing dependency with v5.1.1.
