### ISSUE TITLE
Add styles tab to bottom

### ISSUE THREAD

**Issue by emsuiko** [Malvid/Malvid#29]
Our webdesigner asked if it is possible to add another tab to the bottom row (next to view, data and notes) w/ the contents of the styles-file (e.g. sass).

![mockup for additional styles tag](https://user-images.githubusercontent.com/4366030/49283825-1d13b200-f493-11e8-96d8-680ace6ea1ef.png)

**Comment by emsuiko** [comment]
Awesome, thanks! 👍

**Comment by electerious** [comment]
It's now easier to add custom tabs/resolvers as the default resolvers are available to require: https://github.com/Malvid/Malvid/blob/master/docs/Inspector%20tabs.md
