### ISSUE TITLE
Custom CSS possible?

### ISSUE THREAD

**Issue by emsuiko** [Malvid/Malvid#33]
Hey there 👋 

Is it possible to add a custom style to Malvid?
Example: The iframe has a padding of .5em and we'd like to change that. And some styling in the list on the left as well etc. 😉 

I searched the options but couldn't find anything along these lines.

**Comment by electerious** [comment]
There's currently no way to inject custom styles, but I agree that it might be helpful.

Do you think that a `styles` option that accepts a string would be sufficient?

**Comment by emsuiko** [comment]
Discussed this with out webdesigner. We think a separate styles file would be better, and I guess the path to said file would be configured in the options..?

**Comment by electerious** [comment]
I've been thinking about it and I guess that a string would be better. It would allow you to require, load or preprocess your files in Node.js and then passing the result as a string to Malvid. This would cover more cases than a path.

A `styles` option would be a good addition. Will add this by time.

**Comment by electerious** [comment]
A new `style` and `script` option has been added in version 5.4: https://github.com/Malvid/Malvid/blob/master/docs/Options.md#style
