### ISSUE TITLE
Malvid and gulp

### ISSUE THREAD

**Issue by jpucheavoristravel** [Malvid/Malvid#42]
Hello, 

If posible use malvid in gulp? If this is posible, Can you show a little example? 

Thanks

**Comment by emsuiko** [comment]
Hey there,

you can build with gulp, it's here in the docs: https://github.com/Malvid/Malvid/blob/master/docs/Integrations.md#gulp

We have it integrated as gulp task, without the server/live reload part tho.

**Comment by jpucheavoristravel** [comment]
Thanks! I don't see this file.
