### ISSUE TITLE
Not found error when running through Get Started process

### ISSUE THREAD

**Issue by MikeHarrison** [Malvid/Malvid#9]
Hi,

I have run through the get started process for Malvid, and all looks to have worked as detailed but when I view the site (I am using MAMP as my local server), I get an error in the window where the component should be previewed:

```
Not Found

The requested URL /button.html was not found on this server.
```

The window looks like this:

![screen shot 2018-07-19 at 23 22 32](https://user-images.githubusercontent.com/6464063/42973511-427d16b8-8bab-11e8-904a-1cf7a0627d66.png)

Everything else looks fine - View and Data is correct, and I have tested Notes which work too. No errors in my console either.

The iframe has this as the `src`:

```
<iframe class="css-wlce9h" src="/button.html">
```

Any ideas where I might be going wrong? Looks like a great tool if I can get it working!

**Comment by electerious** [comment]
Hi, looks like I made an error in the guide. The preview files are inside `src` but the UI is inside `dist`. It's therefore not possible for the UI to show a preview. The setup only makes sense in a workflow with a tool that creates the `dist` folder, copies `src` into it, generates the preview files and runs Malvid. But that's not the case here.

I've adjusted the guide: https://github.com/Malvid/Malvid/commit/a11a885db231eb888f187fc3021cf2524b354e5d

Here's the new one: https://github.com/Malvid/Malvid/blob/master/docs/Get%20started.md
